[package]
name = "basil-frontend"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
basil-lexer    = { workspace = true }
basil-parser   = { workspace = true }
basil-ast      = { workspace = true }
basil-common   = { workspace = true }
